
        const labels = { charge_fee: 'Charge Fee', retry_payment: 'Retry Payment', offer_waitlist: 'Offer Waitlist', friendly_reminder: 'Friendly Reminder', escalate_human: 'Needs Review' };
        let clients = [], selected = new Set(); const rows = document.querySelector('#rows'), error = document.querySelector('#error');
        const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
        const ago = value => { const time = new Date(value ?? '').getTime(); if (!value || Number.isNaN(time)) return '—'; const seconds = Math.max(0, (Date.now() - time) / 1000); if (seconds < 60) return 'just now'; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return `${Math.floor(seconds / 86400)}d ago` };
        const stamp = value => { const date = new Date(value ?? ''); if (!value || Number.isNaN(date.getTime())) return '—'; return date.toLocaleString(undefined, { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) };
        function visible() { const c = document.querySelector('#condition').value, s = document.querySelector('#status').value; return clients.filter(x => (!c || x.condition === c) && (!s || (s === 'sent') === x.email_sent)) }
        function render() { const list = visible(); rows.innerHTML = list.length ? list.map(x => `<tr data-id="${escapeHtml(x.client_id)}"><td><input class="pick" type="checkbox" ${selected.has(x.client_id) ? 'checked' : ''} ${!x.can_send || x.email_sent ? 'disabled' : ''} aria-label="Select ${escapeHtml(x.name)}"></td><td><span class="name">${escapeHtml(x.name)}</span><span class="email">${escapeHtml(x.email || 'No email')}</span></td><td><span class="badge ${escapeHtml(x.condition)}">${escapeHtml(labels[x.condition] || x.condition)}</span></td><td><span class="status ${x.email_sent ? 'sent' : ''}">${x.email_sent ? 'Sent' : 'Not sent'}</span></td><td>${x.email_sent ? `<span title="${escapeHtml(x.last_email_sent_at)}">${escapeHtml(stamp(x.last_email_sent_at))}</span>` : '—'}</td><td>${x.email_sent ? `<div class="action-state"><span class="last">Last sent ${escapeHtml(ago(x.last_email_sent_at))}</span><button class="resend">Resend</button></div>` : `<button class="send primary" ${x.can_send ? '' : 'disabled'}>${x.can_send ? 'Send Email' : 'Unavailable'}</button>`}</td></tr>`).join('') : '<tr><td colspan="6" class="empty">No clients match these filters.</td></tr>'; document.querySelector('#bulk').disabled = !selected.size }
        function showError(message) { error.textContent = message; error.style.display = message ? 'block' : 'none' }
        async function load() { const response = await fetch('/api/clients'); if (!response.ok) throw new Error('Could not load clients'); clients = await response.json(); const filter = document.querySelector('#condition'), keep = filter.value, conditions = [...new Set(clients.map(x => x.condition))].sort(); filter.innerHTML = '<option value="">All conditions</option>' + conditions.map(x => `<option value="${escapeHtml(x)}">${escapeHtml(labels[x] || x)}</option>`).join(''); if (conditions.includes(keep)) filter.value = keep; render() }
        async function send(id, resend = false) { const response = await fetch(`/api/clients/${encodeURIComponent(id)}/send-email`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resend }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Email failed'); clients = clients.map(x => x.client_id === id ? { ...x, ...data } : x); selected.delete(id); render() }
        rows.addEventListener('click', async event => { const tr = event.target.closest('tr[data-id]'); if (!tr) return; const id = tr.dataset.id, client = clients.find(x => x.client_id === id); if (event.target.classList.contains('pick')) { event.stopPropagation(); event.target.checked ? selected.add(id) : selected.delete(id); render(); return } if (event.target.classList.contains('send')) { event.stopPropagation(); event.target.disabled = true; try { showError(''); await send(id) } catch (e) { showError(e.message); render() } return } if (event.target.classList.contains('resend')) { event.stopPropagation(); if (confirm(`Resend the current ${labels[client.condition] || client.condition} email to ${client.email}?`)) { try { showError(''); await send(id, true) } catch (e) { showError(e.message) } } return } document.querySelector('#drawer-title').textContent = client.name; const badge = document.querySelector('#drawer-condition'); badge.className = `badge ${client.condition}`; badge.textContent = labels[client.condition] || client.condition; document.querySelector('#case').textContent = JSON.stringify(client.case, null, 2); document.querySelector('#drawer').classList.add('open'); document.querySelector('#drawer').setAttribute('aria-hidden', 'false') });
        document.querySelector('#close').onclick = () => { document.querySelector('#drawer').classList.remove('open'); document.querySelector('#drawer').setAttribute('aria-hidden', 'true') }; document.querySelectorAll('select').forEach(x => x.onchange = render); document.querySelector('#all').onchange = e => { visible().filter(x => x.can_send && !x.email_sent).forEach(x => e.target.checked ? selected.add(x.client_id) : selected.delete(x.client_id)); render() }; document.querySelector('#bulk').onclick = async () => { const ids = [...selected]; if (!ids.length) return; const response = await fetch('/api/clients/send-bulk', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ client_ids: ids }) }); const data = await response.json(); if (!response.ok) { showError(data.error || 'Bulk send failed'); return } showError(data.failed ? `${data.sent} sent; ${data.failed} failed: ${data.errors.map(x => x.error).join(', ')}` : ''); selected.clear(); await load() }; load().catch(e => { rows.innerHTML = '<tr><td colspan="6" class="empty">Unable to load clients.</td></tr>'; showError(e.message) });
    